name       : cuppa
version    : 1.0
release    : 1
source     :
    - https://github.com/DataDrake/cuppa/archive/v1.0.tar.gz : ad02578a2d4f3400bac44dcb372668eda2407e0b0802708d75e524b3ac1b9696
license    : Apache-2.0
component  : programming.tools
summary    : Comprehensive Upstream Provider Polling Assistant
description: |
    As a package maintainer, it's a challenging task to keep track of every new release of a piece of software. Usually this involves subscribing to mailing lists, signing up for notifications from FOSS portals like Github, or even subscribing to news sites. For a distro, this might also mean a repeated effort amongst its package maintainers. The inefficiency and time requirements of such an approach is inevitable. This has led several distros to create their own upstream tracking platforms to automate the process of tracking upstream releases. However, these platforms are often distro specific, leading to further duplication of effort between distros.
builddeps  :
    - git
    - golang
networking : yes
build      : |
    %make
install    : |
    %make_install
